"""Agent Orchestrator - Multi-step agentic reasoning engine."""
from typing import Dict, Any, List, Optional
from datetime import datetime
from dataclasses import dataclass
import logging
import json
import re
import time

logger = logging.getLogger(__name__)


@dataclass
class AgentStep:
    """Single step in agent execution."""
    step_id: str
    tool_name: str
    tool_input: Dict[str, Any]
    result: Optional[Dict[str, Any]] = None
    error: Optional[str] = None
    execution_time_ms: float = 0.0
    timestamp: datetime = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.utcnow()
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "step_id": self.step_id,
            "tool_name": self.tool_name,
            "tool_input": self.tool_input,
            "result": self.result,
            "error": self.error,
            "execution_time_ms": self.execution_time_ms,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class AgentPlan:
    """Execution plan generated by LLM."""
    goal: str
    steps: List[Dict[str, Any]]
    reasoning: str = ""
    estimated_steps: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "goal": self.goal,
            "steps": self.steps,
            "reasoning": self.reasoning,
            "estimated_steps": self.estimated_steps,
        }


class AgentOrchestrator:
    """Orchestrates multi-step agentic reasoning and execution."""
    
    def __init__(
        self,
        llm_service,
        tool_registry,
        memory_store=None,
        reflection_service=None,
        max_steps: int = 10,
        max_retries: int = 2,
    ):
        """Initialize agent orchestrator.
        
        Args:
            llm_service: LLMService instance for reasoning
            tool_registry: ToolRegistry with available tools
            memory_store: Optional MemoryStore for conversation history
            reflection_service: Optional ReflectionService for validation
            max_steps: Maximum steps per agent task
            max_retries: Max retries for failed steps
        """
        self.llm_service = llm_service
        self.tool_registry = tool_registry
        self.memory_store = memory_store
        self.reflection_service = reflection_service
        self.max_steps = max_steps
        self.max_retries = max_retries
    
    async def execute_agent_task(
        self,
        user_id: int,
        goal: str,
        context: Optional[str] = None,
        constraints: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """Execute multi-step agentic task with planning and reflection.
        
        Args:
            user_id: User ID for memory/context
            goal: High-level goal/query
            context: Optional additional context
            constraints: Optional list of constraints (no_tool_X, etc.)
            
        Returns:
            Final result with execution trace
        """
        task_start = time.time()
        task_id = f"agent_task_{int(task_start)}"
        
        logger.info(f"[{task_id}] Starting agentic task: {goal}")
        
        try:
            # Step 1: Get conversation memory context
            memory_context = ""
            if self.memory_store:
                memory = await self.memory_store.get_or_create_memory(user_id)
                memory_context = await memory.get_context(limit=5)
                await memory.add_message("user", goal, metadata={"task_id": task_id})
            
            # Step 2: Generate plan
            plan = await self._generate_plan(
                goal=goal,
                context=context,
                memory_context=memory_context,
                constraints=constraints,
            )
            
            logger.info(f"[{task_id}] Generated plan with {len(plan.steps)} steps")
            logger.debug(f"[{task_id}] Plan reasoning: {plan.reasoning}")
            
            # Step 3: Execute steps
            execution_results = {}
            executed_steps = []
            
            for step_idx, step_plan in enumerate(plan.steps[:self.max_steps]):
                step_id = f"step_{step_idx + 1}"
                
                # Extract tool info
                tool_name = step_plan.get("tool")
                tool_input = step_plan.get("input", {})
                
                if not tool_name:
                    logger.warning(f"[{task_id}] Invalid step plan: no tool specified")
                    continue
                
                # Execute step with retry logic
                step_result = await self._execute_step_with_retry(
                    task_id=task_id,
                    step_id=step_id,
                    tool_name=tool_name,
                    tool_input=tool_input,
                )
                
                executed_steps.append(step_result)
                execution_results[step_id] = step_result.result or step_result.error
                
                # Early exit on failure if critical
                if step_result.error and step_plan.get("critical", False):
                    logger.error(f"[{task_id}] Critical step {step_id} failed, aborting")
                    break
            
            # Step 4: Synthesize final answer
            final_answer = await self._synthesize_answer(
                task_id=task_id,
                goal=goal,
                execution_results=execution_results,
                execution_steps=executed_steps,
            )
            
            # Step 5: Optional reflection and refinement
            if self.reflection_service:
                final_answer = await self.reflection_service.validate_and_refine(
                    answer=final_answer.get("answer", ""),
                    context=context or goal,
                )
            
            # Store in memory
            if self.memory_store:
                memory = await self.memory_store.get_or_create_memory(user_id)
                await memory.add_message(
                    "assistant",
                    final_answer.get("answer", ""),
                    metadata={
                        "task_id": task_id,
                        "steps_executed": len(executed_steps),
                        "success": True,
                    },
                )
            
            task_time_ms = (time.time() - task_start) * 1000
            
            result = {
                "task_id": task_id,
                "status": "completed",
                "goal": goal,
                "answer": final_answer.get("answer", ""),
                "reasoning": final_answer.get("reasoning", ""),
                "execution_steps": [s.to_dict() for s in executed_steps],
                "total_steps": len(executed_steps),
                "total_time_ms": task_time_ms,
            }
            
            logger.info(f"[{task_id}] Task completed in {task_time_ms:.0f}ms with {len(executed_steps)} steps")
            return result
            
        except Exception as e:
            logger.error(f"[{task_id}] Task failed: {str(e)}")
            
            # Store failure in memory
            if self.memory_store:
                try:
                    memory = await self.memory_store.get_or_create_memory(user_id)
                    await memory.add_message(
                        "assistant",
                        f"Task failed with error: {str(e)}",
                        metadata={"task_id": task_id, "success": False},
                    )
                except:
                    pass
            
            return {
                "task_id": task_id,
                "status": "failed",
                "goal": goal,
                "error": str(e),
                "total_time_ms": (time.time() - task_start) * 1000,
            }
    
    async def _generate_plan(
        self,
        goal: str,
        context: Optional[str],
        memory_context: str,
        constraints: Optional[List[str]],
    ) -> AgentPlan:
        """Generate execution plan using LLM.
        
        Args:
            goal: Task goal
            context: Additional context
            memory_context: Conversation history
            constraints: Execution constraints
            
        Returns:
            AgentPlan with steps
        """
        tools_description = self.tool_registry.get_tools_prompt()
        
        constraints_str = ""
        if constraints:
            constraints_str = f"Constraints: {', '.join(constraints)}\n"
        
        memory_str = f"Conversation history:\n{memory_context}\n\n" if memory_context else ""
        
        prompt = f"""You are an intelligent agent planner. Analyze the goal and create an execution plan using available tools.

{memory_str}
Available Tools:
{tools_description}

{constraints_str}
Goal: {goal}

{f'Additional Context: {context}' if context else ''}

Generate a JSON plan with these exact fields:
{{
    "reasoning": "brief explanation of approach",
    "steps": [
        {{"tool": "tool_name", "input": {{"param1": "value1", "param2": "value2"}}, "critical": false}}
    ]
}}

Important:
- Use ONLY tools from the available list
- Each step must have valid parameters for the tool
- Keep total steps <= 5 for efficiency
- Set "critical": true only for steps that affect the final outcome
- Return ONLY valid JSON, no markdown or explanation
"""
        
        result = await self.llm_service.generate(prompt=prompt, temperature=0.3)
        text = result.get("text", "")
        
        # Parse plan
        plan_dict = self._safe_parse_json(text)
        
        if not plan_dict or "steps" not in plan_dict:
            logger.warning("Failed to parse plan, using simple fallback")
            plan_dict = {
                "reasoning": "Direct execution of goal",
                "steps": [{"tool": "search_documents", "input": {"query": goal}, "critical": True}],
            }
        
        return AgentPlan(
            goal=goal,
            steps=plan_dict.get("steps", []),
            reasoning=plan_dict.get("reasoning", ""),
            estimated_steps=len(plan_dict.get("steps", [])),
        )
    
    async def _execute_step_with_retry(
        self,
        task_id: str,
        step_id: str,
        tool_name: str,
        tool_input: Dict[str, Any],
    ) -> AgentStep:
        """Execute a single step with retry logic.
        
        Args:
            task_id: Task ID for logging
            step_id: Step ID
            tool_name: Tool to execute
            tool_input: Tool input parameters
            
        Returns:
            AgentStep with result
        """
        step_start = time.time()
        tool = self.tool_registry.get_tool(tool_name)
        
        if not tool:
            error_msg = f"Tool not found: {tool_name}"
            logger.error(f"[{task_id}] {step_id}: {error_msg}")
            return AgentStep(
                step_id=step_id,
                tool_name=tool_name,
                tool_input=tool_input,
                error=error_msg,
                execution_time_ms=(time.time() - step_start) * 1000,
            )
        
        for attempt in range(self.max_retries):
            try:
                logger.info(f"[{task_id}] {step_id}: Executing {tool_name} (attempt {attempt + 1})")
                
                # Execute tool
                tool_result = await tool.execute(**tool_input)
                
                if tool_result.success:
                    logger.info(f"[{task_id}] {step_id}: Success")
                    return AgentStep(
                        step_id=step_id,
                        tool_name=tool_name,
                        tool_input=tool_input,
                        result=tool_result.data,
                        execution_time_ms=(time.time() - step_start) * 1000,
                    )
                else:
                    error_msg = tool_result.error or "Unknown error"
                    logger.warning(f"[{task_id}] {step_id}: Tool failed: {error_msg}")
                    
                    if attempt < self.max_retries - 1:
                        logger.info(f"[{task_id}] {step_id}: Retrying...")
                        continue
                    else:
                        return AgentStep(
                            step_id=step_id,
                            tool_name=tool_name,
                            tool_input=tool_input,
                            error=error_msg,
                            execution_time_ms=(time.time() - step_start) * 1000,
                        )
                        
            except Exception as e:
                logger.error(f"[{task_id}] {step_id}: Exception: {str(e)}")
                
                if attempt < self.max_retries - 1:
                    continue
                
                return AgentStep(
                    step_id=step_id,
                    tool_name=tool_name,
                    tool_input=tool_input,
                    error=str(e),
                    execution_time_ms=(time.time() - step_start) * 1000,
                )
        
        # Should not reach here
        return AgentStep(
            step_id=step_id,
            tool_name=tool_name,
            tool_input=tool_input,
            error="Max retries exceeded",
            execution_time_ms=(time.time() - step_start) * 1000,
        )
    
    async def _synthesize_answer(
        self,
        task_id: str,
        goal: str,
        execution_results: Dict[str, Any],
        execution_steps: List[AgentStep],
    ) -> Dict[str, Any]:
        """Synthesize final answer from execution results.
        
        Args:
            task_id: Task ID
            goal: Original goal
            execution_results: Results from all steps
            execution_steps: Detailed step information
            
        Returns:
            Dictionary with answer and reasoning
        """
        # Format execution results for context
        results_str = json.dumps(execution_results, indent=2, default=str)
        
        prompt = f"""You are synthesizing final results from an agent task.

Original Goal: {goal}

Execution Results:
{results_str}

Based on these results, provide:
1. A clear, concise final answer to the original goal
2. Brief reasoning explaining how the results lead to this answer
3. Any actionable insights or next steps

Return ONLY valid JSON:
{{
    "answer": "clear final answer",
    "reasoning": "explanation of how results led to this answer",
    "confidence": 0.8,
    "next_steps": ["optional action item 1", "optional action item 2"]
}}
"""
        
        result = await self.llm_service.generate(prompt=prompt, temperature=0.3)
        text = result.get("text", "")
        
        parsed = self._safe_parse_json(text)
        
        if not parsed or "answer" not in parsed:
            # Fallback: extract first successful tool result
            for step in execution_steps:
                if step.result:
                    return {
                        "answer": json.dumps(step.result, default=str)[:500],
                        "reasoning": "Extracted from first successful step",
                        "confidence": 0.5,
                        "next_steps": [],
                    }
            
            return {
                "answer": f"Goal: {goal} - No conclusive results available",
                "reasoning": "No successful tool executions",
                "confidence": 0.0,
                "next_steps": [],
            }
        
        return parsed
    
    def _safe_parse_json(self, text: str) -> Optional[Dict[str, Any]]:
        """Safely parse JSON from LLM response.
        
        Args:
            text: Text to parse
            
        Returns:
            Parsed dictionary or None
        """
        try:
            # Remove markdown code blocks
            cleaned = re.sub(r"```json|```", "", text).strip()
            
            # Try to find JSON object
            match = re.search(r"\{.*\}", cleaned, re.DOTALL)
            if match:
                return json.loads(match.group())
            
            return json.loads(cleaned)
        except Exception as e:
            logger.debug(f"Failed to parse JSON: {str(e)}")
            return None
